import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:lucide_icons/lucide_icons.dart';
import '../../services/supabase_service.dart';

class CurriculumReviewPanel extends StatefulWidget {
  final bool isDarkMode;
  final Map<String, dynamic> userData;

  const CurriculumReviewPanel(
      {super.key, required this.isDarkMode, required this.userData});

  @override
  State<CurriculumReviewPanel> createState() => _CurriculumReviewPanelState();
}

class _CurriculumReviewPanelState extends State<CurriculumReviewPanel> {
  final TextEditingController _searchController = TextEditingController();
  final SupabaseService _service = SupabaseService();

  int _activeStep = 0; // 0: Queue, 1: Loading, 2: Review, 3: Finalized
  final Set<String> _selectedStudentIds = {};
  Map<String, dynamic>? _selectedStudent;

  // --- DATABASE DATA ---
  List<Map<String, dynamic>> _facultyList = [];
  List<Map<String, dynamic>> _subjectCatalog = [];

  // --- LOCAL SYSTEM STORAGE (Session-based Templates) ---
  static final List<Map<String, dynamic>> _localTemplates = [];

  String? _chairDepartmentId;
  String? _chairDepartmentName;
  bool _isContextLoading = true;
  String? _errorMessage;

  // --- FORM SELECTIONS ---
  String? _selectedSubjectId;
  String? _autoGeneratedBlock;

  // AUTO-FILL READ ONLY STATE
  String? _autoFilledFacultyId;
  String? _autoFilledFacultyName;
  String? _autoFilledDay;
  String? _autoFilledTime;

  final List<String> _timeSlots = [
    "07:30 AM - 09:00 AM",
    "09:00 AM - 10:30 AM",
    "10:30 AM - 12:00 PM",
    "01:00 PM - 02:30 PM",
    "02:30 PM - 04:00 PM",
    "04:00 PM - 05:30 PM"
  ];

  static const Color aViolet = Color(0xFF8B5CF6);
  static const Color success = Color(0xFF69F0AE);
  static const Color surfaceDark = Color(0xFF1E1B4B);
  static const Color pViolet = Color(0xFF2E1065);

  List<Map<String, dynamic>> _assignedSubjects = [];
  double get _totalUnits => _assignedSubjects.fold(0.0,
      (sum, item) => sum + (double.tryParse(item['units'].toString()) ?? 0.0));

  @override
  void initState() {
    super.initState();
    _initChairContext();
  }

  /// 🛰️ STEP 1: RESOLVE DEPARTMENT CONTEXT
  Future<void> _initChairContext() async {
    if (!mounted) return;
    setState(() {
      _isContextLoading = true;
      _errorMessage = null;
    });

    final String? resolvedIdNum = widget.userData['user_id_number']?.toString();
    if (resolvedIdNum == null) return;

    try {
      final response = await _service.getChairContext(resolvedIdNum);
      if (response != null && response['department_id'] != null) {
        setState(() {
          _chairDepartmentId = response['department_id']?.toString();
          _chairDepartmentName = response['departments']?['name']?.toString() ??
              "Institutional Unit";
        });
        await _loadMasterData();
      }
    } catch (e) {
      if (mounted) setState(() => _errorMessage = "Database Sync Error: $e");
    } finally {
      if (mounted) setState(() => _isContextLoading = false);
    }
  }

  /// 🛰️ STEP 2: LOAD MASTER DATA
  Future<void> _loadMasterData() async {
    if (_chairDepartmentId == null) return;
    try {
      final List<dynamic> catalogResponse =
          await _service.client.from('subjects').select('*');
      final facultyResponse =
          await _service.getFacultyForChair(_chairDepartmentId!);

      if (mounted) {
        setState(() {
          _facultyList = List<Map<String, dynamic>>.from(facultyResponse);
          _subjectCatalog = List<Map<String, dynamic>>.from(catalogResponse);
        });
      }
    } catch (e) {
      debugPrint("Load Master Data Error: $e");
    }
  }

  /// 🛰️ SMART AUTO-FILL: Fetches data from the "Master Schedule" (Faculty Load Panel)
  Future<void> _autoFillFromMasterSchedule(String subjectId) async {
    try {
      final response = await _service.client
          .from('study_loads')
          .select(
              'professor_id, day_schedule, time_start, time_end, profiles!study_loads_professor_id_fkey(fn, ln)')
          .eq('subject_id', subjectId)
          .filter('student_id', 'is', null)
          .limit(1)
          .maybeSingle();

      if (response != null && mounted) {
        setState(() {
          _autoFilledFacultyId = response['professor_id'].toString();
          final prof = response['profiles'];
          _autoFilledFacultyName = prof != null
              ? "${prof['fn']} ${prof['ln']}"
              : "ASSIGNED PROFESSOR";
          _autoFilledDay = response['day_schedule'];
          _autoFilledTime =
              "${response['time_start']} - ${response['time_end']}";
        });
        _showToast(
            "Auto-filled schedule from Faculty Load.", Colors.blueAccent);
      } else {
        setState(() {
          _autoFilledFacultyId = null;
          _autoFilledFacultyName = "UNASSIGNED";
          _autoFilledDay = "N/A";
          _autoFilledTime = "N/A";
        });
        _showToast("No master schedule found. Assign a professor first.",
            Colors.orangeAccent);
      }
    } catch (e) {
      debugPrint("Master Schedule Sync Error: $e");
    }
  }

  /// 💾 LOCAL TEMPLATE ACTIONS
  void _saveAsTemplate(String templateName) {
    if (_assignedSubjects.isEmpty) return;
    setState(() {
      _localTemplates.add({
        'id': DateTime.now().millisecondsSinceEpoch.toString(),
        'name': templateName,
        'subjects_data': List<Map<String, dynamic>>.from(_assignedSubjects),
      });
    });
    _showToast("Template '$templateName' saved locally.", success);
  }

  void _applyTemplate(Map<String, dynamic> template) {
    setState(() {
      final List<dynamic> data = template['subjects_data'];
      _assignedSubjects = List<Map<String, dynamic>>.from(data);
    });
    _showToast("Applied template: ${template['name']}", aViolet);
  }

  /// 📐 LOGIC: Generate Block
  Future<String> _generateDynamicBlock(
      String courseCode, String yearLevel) async {
    final String yearNum = yearLevel.replaceAll(RegExp(r'[^0-9]'), '');
    final String baseBlock = "$courseCode-$yearNum";
    try {
      final List<dynamic> roster = await _service.client
          .from('student_details')
          .select('profile_id')
          .eq('courses!inner(code)', courseCode)
          .eq('year_levels!inner(definition)', yearLevel);
      if (roster.length < 50) return baseBlock;
      int sectionIndex = roster.length ~/ 50;
      return "$baseBlock${String.fromCharCode(65 + sectionIndex)}";
    } catch (e) {
      return baseBlock;
    }
  }

  Future<void> _handleStepTransition(Map<String, dynamic> student) async {
    setState(() => _isContextLoading = true);
    final details = student['student_details'];
    Map<String, dynamic>? studentInfo =
        (details is List && details.isNotEmpty) ? details[0] : details;

    if (studentInfo == null) {
      _showToast("Missing Student Record Details.", Colors.redAccent);
      setState(() => _isContextLoading = false);
      return;
    }

    final String cCode = (studentInfo['courses']?['code'] ?? "GEN").toString();
    final String yLevel =
        (studentInfo['year_levels']?['definition'] ?? "1st Year").toString();
    final block = await _generateDynamicBlock(cCode, yLevel);

    setState(() {
      _selectedStudent = student;
      _autoGeneratedBlock = block;
      _isContextLoading = false;
      _activeStep = 1;
    });
  }

  /// 🛰️ FINALIZATION:
  /// Now updates status to 'Assessment' to alert Accounting
  Future<void> _finalizeStudyLoads() async {
    if (_assignedSubjects.isEmpty) return;
    setState(() => _isContextLoading = true);

    final targetIds = _selectedStudentIds.isNotEmpty
        ? _selectedStudentIds.toList()
        : [_selectedStudent!['id']];

    try {
      List<Map<String, dynamic>> studyLoads = [];
      for (String sId in targetIds) {
        for (var sub in _assignedSubjects) {
          studyLoads.add({
            'student_id': sId,
            'subject_id': sub['id'],
            'professor_id': sub['professor_id'],
            'section_block': sub['block'],
            'day_schedule': sub['day'],
            'time_start': sub['time'].split(' - ')[0],
            'time_end': sub['time'].split(' - ')[1],
          });
        }
      }

      // 1. Assign the subjects
      await _service.batchAssignSubjects(studyLoads);

      // 2. Transmit to Accounting (Update Status)
      // FIX: Changed "Pending Assessment" to "Assessment" to resolve DB check constraint violation
      for (String sId in targetIds) {
        await _service.client
            .from('student_details')
            .update({'enrollment_status': 'Assessment'}).eq('profile_id', sId);
      }

      if (mounted) {
        setState(() {
          _activeStep = 3;
          _selectedStudentIds.clear();
          _assignedSubjects = [];
          _isContextLoading = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isContextLoading = false);
        _showToast("Sync Error: $e", Colors.redAccent);
      }
    }
  }

  void _addSubjectToSession() {
    if (_selectedSubjectId == null || _autoFilledFacultyId == null) return;

    final subject = _subjectCatalog
        .firstWhere((s) => s['id'].toString() == _selectedSubjectId);

    setState(() {
      _assignedSubjects.add({
        "id": subject['id'],
        "code": subject['code'],
        "title": subject['name'],
        "units": subject['units'],
        "professor_id": _autoFilledFacultyId,
        "professor_name": _autoFilledFacultyName,
        "block": _autoGeneratedBlock,
        "day": _autoFilledDay,
        "time": _autoFilledTime,
      });
      _selectedSubjectId = null;
      _autoFilledFacultyId = null;
      _autoFilledFacultyName = null;
      _autoFilledDay = null;
      _autoFilledTime = null;
    });
  }

  @override
  Widget build(BuildContext context) {
    final textColor = widget.isDarkMode ? Colors.white : pViolet;
    final bgColor = widget.isDarkMode ? surfaceDark : Colors.white;

    if (_isContextLoading) {
      return const Center(child: CircularProgressIndicator(color: aViolet));
    }
    if (_errorMessage != null) {
      return _buildErrorState(_errorMessage!, textColor);
    }

    return SingleChildScrollView(
      physics: const BouncingScrollPhysics(),
      padding: const EdgeInsets.all(40),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildHeader(textColor),
          const SizedBox(height: 32),
          _buildWorkflowStepper(textColor),
          const SizedBox(height: 32),
          _buildActiveModuleContent(textColor, bgColor),
        ],
      ),
    );
  }

  Widget _buildActiveModuleContent(Color textColor, Color bgColor) {
    switch (_activeStep) {
      case 0:
        return _buildStudentQueue(textColor, bgColor);
      case 1:
        return _buildSubjectLoadingInterface(textColor, bgColor);
      case 2:
        return _buildReviewModule(textColor, bgColor);
      case 3:
        return _buildHandoverSuccess(textColor, bgColor);
      default:
        return _buildStudentQueue(textColor, bgColor);
    }
  }

  Widget _buildStudentQueue(Color textColor, Color bgColor) {
    if (_chairDepartmentId == null) return _buildEmptyState(textColor);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Expanded(child: _buildSearchBar(bgColor, textColor)),
            if (_selectedStudentIds.isNotEmpty) ...[
              const SizedBox(width: 16),
              ElevatedButton.icon(
                onPressed: () => setState(() => _activeStep = 1),
                icon: const Icon(LucideIcons.users),
                label: Text(
                    "BATCH ASSIGN (${_selectedStudentIds.length} STUDENTS)"),
                style: ElevatedButton.styleFrom(
                    backgroundColor: aViolet,
                    padding: const EdgeInsets.all(22)),
              ),
            ]
          ],
        ),
        const SizedBox(height: 24),
        FutureBuilder<List<Map<String, dynamic>>>(
          future: _service.getStudentQueue(_chairDepartmentId!),
          builder: (context, snapshot) {
            if (!snapshot.hasData) {
              return const Center(
                  child: CircularProgressIndicator(color: aViolet));
            }
            final list = snapshot.data!.where((s) {
              return s['fn']
                  .toString()
                  .toLowerCase()
                  .contains(_searchController.text.toLowerCase());
            }).toList();
            if (list.isEmpty) return _buildEmptyState(textColor);

            return ListView.builder(
              shrinkWrap: true,
              physics: const NeverScrollableScrollPhysics(),
              itemCount: list.length,
              itemBuilder: (context, i) {
                final s = list[i];
                bool isSelected = _selectedStudentIds.contains(s['id']);
                final details = s['student_details'];
                Map<String, dynamic>? info =
                    (details is List && details.isNotEmpty)
                        ? details[0]
                        : details;
                bool isIrreg = info?['student_type'] == 'Irregular';

                return Container(
                  margin: const EdgeInsets.only(bottom: 12),
                  padding: const EdgeInsets.all(20),
                  decoration: BoxDecoration(
                      color: bgColor,
                      borderRadius: BorderRadius.circular(16),
                      border: Border.all(
                          color: isSelected ? aViolet : Colors.white10)),
                  child: Row(
                    children: [
                      Checkbox(
                          value: isSelected,
                          activeColor: aViolet,
                          onChanged: (v) => setState(() => v!
                              ? _selectedStudentIds.add(s['id'])
                              : _selectedStudentIds.remove(s['id']))),
                      const SizedBox(width: 12),
                      Expanded(
                          child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                            Row(children: [
                              Text("${s['fn']} ${s['ln']}",
                                  style: TextStyle(
                                      color: textColor,
                                      fontWeight: FontWeight.bold)),
                              const SizedBox(width: 8),
                              _typeBadge(isIrreg ? 'IRREGULAR' : 'REGULAR',
                                  isIrreg ? Colors.orange : success),
                            ]),
                            Text(
                                "${s['user_id_number']} • ${info?['courses']?['code'] ?? 'N/A'} • ${info?['year_levels']?['definition'] ?? 'N/A'}",
                                style: const TextStyle(
                                    color: Colors.blueGrey, fontSize: 12))
                          ])),
                      ElevatedButton(
                          onPressed: () => _handleStepTransition(s),
                          child: const Text("Assign Subjects")),
                    ],
                  ),
                );
              },
            );
          },
        ),
      ],
    );
  }

  Widget _buildSubjectLoadingInterface(Color textColor, Color bgColor) {
    return Container(
      padding: const EdgeInsets.all(32),
      decoration: BoxDecoration(
          color: bgColor,
          borderRadius: BorderRadius.circular(24),
          border: Border.all(color: Colors.white10)),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                Text("Study Load Configuration",
                    style: GoogleFonts.inter(
                        fontWeight: FontWeight.bold,
                        color: textColor,
                        fontSize: 18)),
                Text("TARGET BLOCK: ${_autoGeneratedBlock ?? 'N/A'}",
                    style: const TextStyle(
                        color: aViolet,
                        fontWeight: FontWeight.bold,
                        fontSize: 12)),
              ]),
              Row(
                children: [
                  _templateActionMenu(textColor),
                  const SizedBox(width: 12),
                  _badge("DEPT: $_chairDepartmentName", aViolet),
                ],
              ),
            ],
          ),
          const Divider(height: 48, color: Colors.white10),
          Row(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Expanded(
                  flex: 3,
                  child: _buildMapDropdown("Institutional Catalog",
                      _selectedSubjectId, _subjectCatalog, (v) {
                    setState(() => _selectedSubjectId = v);
                    if (v != null) _autoFillFromMasterSchedule(v);
                  })),
              const SizedBox(width: 12),
              _readOnlyField("Professor (Master)",
                  _autoFilledFacultyName ?? "Select Subject"),
              const SizedBox(width: 12),
              _readOnlyField("Schedule",
                  "${_autoFilledDay ?? ''} ${_autoFilledTime ?? ''}"),
              const SizedBox(width: 16),
              IconButton(
                  onPressed: _addSubjectToSession,
                  icon: const Icon(LucideIcons.plusCircle,
                      color: success, size: 36)),
            ],
          ),
          const SizedBox(height: 40),
          _buildAssignedList(textColor),
          const SizedBox(height: 32),
          Row(mainAxisAlignment: MainAxisAlignment.end, children: [
            Text("Total Units: $_totalUnits",
                style: GoogleFonts.orbitron(
                    color: textColor,
                    fontWeight: FontWeight.bold,
                    fontSize: 18)),
            const SizedBox(width: 24),
            ElevatedButton(
                onPressed: _assignedSubjects.isEmpty
                    ? null
                    : () => setState(() => _activeStep = 2),
                child: const Text("VALIDATE & REVIEW")),
          ]),
        ],
      ),
    );
  }

  Widget _readOnlyField(String label, String value) => Expanded(
        flex: 2,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(label.toUpperCase(),
                style: const TextStyle(
                    fontSize: 9,
                    fontWeight: FontWeight.bold,
                    color: Colors.blueGrey)),
            const SizedBox(height: 8),
            Container(
              height: 48,
              width: double.infinity,
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 14),
              decoration: BoxDecoration(
                  color: Colors.white.withOpacity(0.05),
                  borderRadius: BorderRadius.circular(10),
                  border: Border.all(color: Colors.white10)),
              child: Text(value,
                  style: const TextStyle(
                      color: Colors.white70,
                      fontSize: 12,
                      overflow: TextOverflow.ellipsis)),
            ),
          ],
        ),
      );

  Widget _templateActionMenu(Color textColor) {
    return PopupMenuButton<String>(
      tooltip: "Load Templates",
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        decoration: BoxDecoration(
            color: aViolet.withOpacity(0.1),
            borderRadius: BorderRadius.circular(10),
            border: Border.all(color: aViolet.withOpacity(0.3))),
        child: const Row(
          children: [
            Icon(LucideIcons.copy, size: 16, color: aViolet),
            SizedBox(width: 8),
            Text("TEMPLATES",
                style: TextStyle(
                    color: aViolet, fontSize: 11, fontWeight: FontWeight.bold)),
          ],
        ),
      ),
      onSelected: (val) {
        if (val == "save_current") {
          _showSaveTemplateDialog();
        } else {
          final template = _localTemplates.firstWhere((t) => t['id'] == val);
          _applyTemplate(template);
        }
      },
      itemBuilder: (context) => [
        const PopupMenuItem(
            value: "save_current",
            child: Row(children: [
              Icon(LucideIcons.save, size: 16, color: success),
              SizedBox(width: 8),
              Text("Save Current as Template")
            ])),
        const PopupMenuDivider(),
        if (_localTemplates.isEmpty)
          const PopupMenuItem(
              enabled: false,
              child: Text("No saved templates",
                  style: TextStyle(color: Colors.grey, fontSize: 12))),
        ..._localTemplates
            .map((t) => PopupMenuItem(value: t['id'], child: Text(t['name']))),
      ],
    );
  }

  void _showSaveTemplateDialog() {
    final nameCtrl = TextEditingController();
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: surfaceDark,
        title: const Text("Save Load Template",
            style: TextStyle(color: Colors.white)),
        content: TextField(
          controller: nameCtrl,
          autofocus: true,
          style: const TextStyle(color: Colors.white),
          decoration: const InputDecoration(
              hintText: "Enter Template Name (e.g. BSIT-2A Regular)"),
        ),
        actions: [
          TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text("CANCEL")),
          ElevatedButton(
              onPressed: () {
                _saveAsTemplate(nameCtrl.text);
                Navigator.pop(context);
              },
              child: const Text("SAVE")),
        ],
      ),
    );
  }

  Widget _buildAssignedList(Color textColor) {
    if (_assignedSubjects.isEmpty) {
      return Center(
          child: Text("No subjects added.",
              style: TextStyle(color: textColor.withOpacity(0.2))));
    }
    return Column(
      children: List.generate(_assignedSubjects.length, (i) {
        final s = _assignedSubjects[i];
        return Container(
          margin: const EdgeInsets.only(bottom: 8),
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
              color: Colors.white.withOpacity(0.02),
              borderRadius: BorderRadius.circular(12)),
          child: Row(
            children: [
              const Icon(LucideIcons.bookOpen, size: 16, color: aViolet),
              const SizedBox(width: 16),
              Expanded(
                  child: Text(s['code'],
                      style: const TextStyle(
                          color: aViolet, fontWeight: FontWeight.bold))),
              Expanded(
                  flex: 2,
                  child: Text(s['professor_name'],
                      style: TextStyle(color: textColor, fontSize: 13))),
              Expanded(
                  flex: 2,
                  child: Text("${s['day']} ${s['time']}",
                      style: const TextStyle(
                          color: Colors.blueGrey, fontSize: 12))),
              IconButton(
                  onPressed: () =>
                      setState(() => _assignedSubjects.removeAt(i)),
                  icon: const Icon(LucideIcons.trash2,
                      size: 16, color: Colors.redAccent)),
            ],
          ),
        );
      }),
    );
  }

  Widget _buildReviewModule(Color textColor, Color bgColor) {
    return Container(
      padding: const EdgeInsets.all(40),
      decoration: BoxDecoration(
          color: bgColor, borderRadius: BorderRadius.circular(24)),
      child: Column(
        children: [
          const Icon(LucideIcons.shieldCheck, color: aViolet, size: 48),
          const SizedBox(height: 24),
          const Text("Academic Compliance Audit",
              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
          const SizedBox(height: 32),
          _auditRow("Faculty Workload Availability Verified", true),
          _auditRow("General Education Resource Check", true),
          _auditRow("Section Block Density Check (Max 50)", true),
          const SizedBox(height: 48),
          SizedBox(
              width: double.infinity,
              height: 65,
              child: ElevatedButton(
                  onPressed: _finalizeStudyLoads,
                  style: ElevatedButton.styleFrom(
                      backgroundColor: success, foregroundColor: Colors.black),
                  child: const Text("APPROVE & TRANSMIT TO ACCOUNTING",
                      style: TextStyle(fontWeight: FontWeight.bold)))),
        ],
      ),
    );
  }

  Widget _buildHandoverSuccess(Color textColor, Color bgColor) {
    return Center(
      child: Column(children: [
        const Icon(LucideIcons.refreshCw, color: success, size: 64),
        const SizedBox(height: 24),
        const Text("Handover Complete",
            style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: Colors.white)),
        const Text("Load data successfully transmitted.",
            style: TextStyle(color: Colors.blueGrey)),
        const SizedBox(height: 40),
        ElevatedButton(
            onPressed: () {
              setState(() {
                _activeStep = 0;
                _assignedSubjects.clear();
                _selectedStudentIds.clear();
                _initChairContext();
              });
            },
            child: const Text("BACK TO QUEUE"))
      ]),
    );
  }

  Widget _buildHeader(Color text) => Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Text("Curriculum Review Console",
                style: GoogleFonts.inter(
                    fontSize: 28,
                    fontWeight: FontWeight.w900,
                    color: text,
                    letterSpacing: -1)),
            Text("Oversight: ${_chairDepartmentName ?? 'Academic Unit'}",
                style: const TextStyle(color: Colors.blueGrey))
          ]),
        ],
      );

  Widget _buildSearchBar(Color bg, Color text) => Container(
      padding: const EdgeInsets.symmetric(horizontal: 16),
      decoration: BoxDecoration(
          color: bg,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: Colors.white10)),
      child: TextField(
          controller: _searchController,
          onChanged: (v) => setState(() {}),
          decoration: const InputDecoration(
              hintText: "Filter queue...",
              prefixIcon: Icon(LucideIcons.search, size: 18),
              border: InputBorder.none)));

  Widget _buildMapDropdown(String label, String? value,
          List<Map<String, dynamic>> items, Function(String?) onChanged) =>
      Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Text(label.toUpperCase(),
            style: const TextStyle(
                fontSize: 9,
                fontWeight: FontWeight.bold,
                color: Colors.blueGrey)),
        const SizedBox(height: 8),
        Container(
            padding: const EdgeInsets.symmetric(horizontal: 12),
            decoration: BoxDecoration(
                color: Colors.white.withOpacity(0.05),
                borderRadius: BorderRadius.circular(10)),
            child: DropdownButtonHideUnderline(
                child: DropdownButton<String>(
                    value: value,
                    isExpanded: true,
                    dropdownColor: surfaceDark,
                    style: const TextStyle(color: Colors.white, fontSize: 12),
                    items: items
                        .map((i) => DropdownMenuItem(
                            value: i['id'].toString(),
                            child: Text(i['name'] ?? "${i['fn']} ${i['ln']}",
                                overflow: TextOverflow.ellipsis)))
                        .toList(),
                    onChanged: onChanged)))
      ]);

  Widget _buildWorkflowStepper(Color text) {
    final steps = ["Queue", "Loading", "Review", "Handover"];
    return Row(
        children: List.generate(steps.length, (i) {
      bool active = i == _activeStep;
      bool done = i < _activeStep;
      return Expanded(
          child: Row(children: [
        Container(
            width: 28,
            height: 28,
            decoration: BoxDecoration(
                color: done ? success : (active ? aViolet : Colors.white10),
                shape: BoxShape.circle),
            child: Center(
                child: done
                    ? const Icon(LucideIcons.check,
                        size: 14, color: Colors.black)
                    : Text("${i + 1}",
                        style: TextStyle(
                            color: active ? Colors.white : Colors.blueGrey,
                            fontSize: 10,
                            fontWeight: FontWeight.bold)))),
        const SizedBox(width: 8),
        Text(steps[i],
            style: TextStyle(
                color: active ? aViolet : Colors.blueGrey,
                fontSize: 11,
                fontWeight: active ? FontWeight.bold : FontWeight.normal)),
        if (i < 3)
          Expanded(
              child: Container(
                  height: 1,
                  color: Colors.white10,
                  margin: const EdgeInsets.symmetric(horizontal: 12))),
      ]));
    }));
  }

  Widget _buildErrorState(String error, Color text) => Center(
          child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
        const Icon(LucideIcons.alertCircle, color: Colors.redAccent, size: 48),
        const SizedBox(height: 16),
        Text(error,
            style: TextStyle(color: text, fontWeight: FontWeight.bold),
            textAlign: TextAlign.center),
        const SizedBox(height: 24),
        ElevatedButton(onPressed: _initChairContext, child: const Text("RETRY"))
      ]));

  Widget _auditRow(String l, bool p) => Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Row(children: [
        Icon(p ? LucideIcons.checkCircle2 : LucideIcons.alertCircle,
            color: p ? success : Colors.orange, size: 18),
        const SizedBox(width: 12),
        Text(l, style: const TextStyle(color: Colors.blueGrey)),
        const Spacer(),
        Text(p ? "PASSED" : "FAILED",
            style: TextStyle(
                color: p ? success : Colors.orange,
                fontSize: 10,
                fontWeight: FontWeight.bold))
      ]));

  Widget _badge(String t, Color c) => Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
      decoration: BoxDecoration(
          color: c.withOpacity(0.1), borderRadius: BorderRadius.circular(8)),
      child: Text(t,
          style:
              TextStyle(color: c, fontSize: 9, fontWeight: FontWeight.bold)));

  Widget _typeBadge(String t, Color c) => Container(
      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
      decoration: BoxDecoration(
          color: c.withOpacity(0.1), borderRadius: BorderRadius.circular(4)),
      child: Text(t,
          style:
              TextStyle(color: c, fontSize: 8, fontWeight: FontWeight.w900)));

  Widget _buildEmptyState(Color t) => Center(
      child: Padding(
          padding: const EdgeInsets.all(40),
          child: Text("Queue empty.",
              style: TextStyle(color: t.withOpacity(0.1)))));

  void _showToast(String m, Color c) =>
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text(m),
          backgroundColor: c,
          behavior: SnackBarBehavior.floating));
}
