import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../services/supabase_service.dart';

class CurriculumReviewPanel extends StatefulWidget {
  final bool isDarkMode;
  final Map<String, dynamic> userData;

  const CurriculumReviewPanel({
    super.key,
    required this.isDarkMode,
    required this.userData,
  });

  @override
  State<CurriculumReviewPanel> createState() => _CurriculumReviewPanelState();
}

class _CurriculumReviewPanelState extends State<CurriculumReviewPanel> {
  final TextEditingController _searchController = TextEditingController();
  final SupabaseService _service = SupabaseService();

  int _activeStep = 0; // 0: Queue, 1: Loading, 2: Review, 3: Finalized
  final Set<String> _selectedStudentIds = {};
  Map<String, dynamic>? _selectedStudent;

  // --- DATABASE DATA ---
  List<Map<String, dynamic>> _subjectCatalog = [];

  // --- LOCAL SYSTEM STORAGE (Session-based Templates) ---
  static final List<Map<String, dynamic>> _localTemplates = [];

  String? _chairDepartmentId;
  String? _chairDepartmentName;
  bool _isContextLoading = true;
  String? _errorMessage;

  // --- FORM SELECTIONS ---
  String? _selectedSubjectId;
  String? _autoGeneratedBlock;

  // --- 🛠️ CHAIR PARAMETER ALLOCATIONS ---
  String _selectedRoom = 'OLC301';
  String _selectedBlock = 'BLOCK A';
  String _selectedSemester = '2nd Semester 2025-2026';

  // --- 📦 MASTER REFERENCE LISTS ---
  final List<String> _availableRooms = [
    'OLC301',
    'OLC302',
    'OLC201',
    'OLC202',
    'SJ102',
    'SJ103',
    'ComLab 1',
    'ComLab 2',
    'Rm 402',
    'Rm 403',
    'TBA'
  ];
  final List<String> _availableBlocks = [
    'BLOCK A',
    'BLOCK B',
    'BLOCK C',
    'TBA'
  ];
  final List<String> _availableSemesters = [
    '1st Semester 2025-2026',
    '2nd Semester 2025-2026',
    'Summer Term 2025-2026'
  ];

  // AUTO-FILL READ ONLY STATE
  String? _autoFilledFacultyId;
  String? _autoFilledFacultyName;
  String? _autoFilledDay;
  String? _autoFilledTime;

  static const Color aViolet = Color(0xFF8B5CF6);
  static const Color success = Color(0xFF69F0AE);
  static const Color surfaceDark = Color(0xFF1E1B4B);
  static const Color pViolet = Color(0xFF2E1065);

  List<Map<String, dynamic>> _assignedSubjects = [];
  double get _totalUnits => _assignedSubjects.fold(0.0,
      (sum, item) => sum + (double.tryParse(item['units'].toString()) ?? 0.0));

  @override
  void initState() {
    super.initState();
    _initChairContext();
  }

  /// 🛰️ STEP 1: RESOLVE DEPARTMENT CONTEXT
  Future<void> _initChairContext() async {
    if (!mounted) return;
    setState(() {
      _isContextLoading = true;
      _errorMessage = null;
    });

    final String? resolvedIdNum = widget.userData['user_id_number']?.toString();
    if (resolvedIdNum == null) return;

    try {
      final response = await _service.getChairContext(resolvedIdNum);
      if (response != null && response['department_id'] != null) {
        setState(() {
          _chairDepartmentId = response['department_id']?.toString();
          _chairDepartmentName = response['departments']?['name']?.toString() ??
              "Institutional Unit";
        });
        await _loadMasterData();
      }
    } catch (e) {
      if (mounted) setState(() => _errorMessage = "Database Sync Error: $e");
    } finally {
      if (mounted) setState(() => _isContextLoading = false);
    }
  }

  /// 🛰️ STEP 2: LOAD MASTER DATA
  Future<void> _loadMasterData() async {
    if (_chairDepartmentId == null) return;
    try {
      final List<dynamic> catalogResponse =
          await _service.client.from('subjects').select('*');

      // Keep fetching faculty context, but avoid mapping to an unused field
      await _service.getFacultyForChair(_chairDepartmentId!);

      if (mounted) {
        setState(() {
          _subjectCatalog = List<Map<String, dynamic>>.from(catalogResponse);
        });
      }
    } catch (e) {
      debugPrint("Load Master Data Error: $e");
    }
  }

  /// 🛰️ SMART AUTO-FILL: Fetches data from the "Master Schedule" (Faculty Load Panel)
  Future<void> _autoFillFromMasterSchedule(String subjectId) async {
    try {
      final response = await _service.client
          .from('study_loads')
          .select(
              'professor_id, day_schedule, time_start, time_end, profiles!study_loads_professor_id_fkey(fn, ln)')
          .eq('subject_id', subjectId)
          .filter('student_id', 'is', null)
          .limit(1)
          .maybeSingle();

      if (response != null && mounted) {
        setState(() {
          _autoFilledFacultyId = response['professor_id'].toString();
          final prof = response['profiles'];
          _autoFilledFacultyName = prof != null
              ? "${prof['fn']} ${prof['ln']}"
              : "ASSIGNED PROFESSOR";
          _autoFilledDay = response['day_schedule'];
          _autoFilledTime =
              "${response['time_start']} - ${response['time_end']}";
        });
        _showToast(
            "Auto-filled schedule from Faculty Load.", Colors.blueAccent);
      } else {
        setState(() {
          _autoFilledFacultyId = null;
          _autoFilledFacultyName = "UNASSIGNED";
          _autoFilledDay = "N/A";
          _autoFilledTime = "N/A";
        });
        _showToast("No master schedule found. Assign a professor first.",
            Colors.orangeAccent);
      }
    } catch (e) {
      debugPrint("Master Schedule Sync Error: $e");
    }
  }

  /// 💾 LOCAL TEMPLATE ACTIONS
  void _saveAsTemplate(String templateName) {
    if (_assignedSubjects.isEmpty) return;
    setState(() {
      _localTemplates.add({
        'id': DateTime.now().millisecondsSinceEpoch.toString(),
        'name': templateName,
        'subjects_data': List<Map<String, dynamic>>.from(_assignedSubjects),
      });
    });
    _showToast("Template '$templateName' saved locally.", success);
  }

  void _applyTemplate(Map<String, dynamic> template) {
    setState(() {
      final List<dynamic> data = template['subjects_data'];
      _assignedSubjects = List<Map<String, dynamic>>.from(data);
    });
    _showToast("Applied template: ${template['name']}", aViolet);
  }

  /// 📐 LOGIC: Generate Block
  Future<String> _generateDynamicBlock(
      String courseCode, String yearLevel) async {
    final String yearNum = yearLevel.replaceAll(RegExp(r'[^0-9]'), '');
    final String baseBlock = "$courseCode-$yearNum";
    try {
      final List<dynamic> roster = await _service.client
          .from('student_details')
          .select('profile_id')
          .eq('courses!inner(code)', courseCode)
          .eq('year_levels!inner(definition)', yearLevel);
      if (roster.length < 50) return "$baseBlock-A";
      int sectionIndex = roster.length ~/ 50;
      return "$baseBlock-${String.fromCharCode(65 + sectionIndex)}";
    } catch (e) {
      return "$baseBlock-A";
    }
  }

  Future<void> _handleStepTransition(Map<String, dynamic> student) async {
    setState(() => _isContextLoading = true);
    final details = student['student_details'];
    Map<String, dynamic>? studentInfo =
        (details is List && details.isNotEmpty) ? details[0] : details;

    if (studentInfo == null) {
      _showToast("Missing Student Record Details.", Colors.redAccent);
      setState(() => _isContextLoading = false);
      return;
    }

    final String cCode = (studentInfo['courses']?['code'] ?? "GEN").toString();
    final String yLevel =
        (studentInfo['year_levels']?['definition'] ?? "1st Year").toString();
    final block = await _generateDynamicBlock(cCode, yLevel);

    setState(() {
      _selectedStudent = student;
      _autoGeneratedBlock = block;
      _selectedBlock = block; // Pre-populate selection to auto-generated block
      _selectedRoom = _availableRooms.first;
      _selectedSemester = _availableSemesters.first;
      _isContextLoading = false;
      _activeStep = 1;
    });
  }

  /// 🛰️ FINALIZATION:
  /// Updates room_number, section_block, day, and times on the database study_loads
  Future<void> _finalizeStudyLoads() async {
    if (_assignedSubjects.isEmpty) return;
    setState(() => _isContextLoading = true);

    final targetIds = _selectedStudentIds.isNotEmpty
        ? _selectedStudentIds.toList()
        : [_selectedStudent!['id']];

    try {
      List<Map<String, dynamic>> studyLoads = [];
      for (String sId in targetIds) {
        for (var sub in _assignedSubjects) {
          String start = 'TBA';
          String end = 'TBA';
          if (sub['time'] != null && sub['time'].toString().contains(' - ')) {
            final parts = sub['time'].toString().split(' - ');
            start = parts[0];
            end = parts[1];
          }

          studyLoads.add({
            'student_id': sId,
            'subject_id': sub['id'],
            'professor_id': sub['professor_id'],
            'section_block':
                sub['block'], // Writes assigned Block (A/B or BSCS-3A)
            'room_number': sub['room'], // Writes assigned Room (OLC301/SJ102)
            'day_schedule': sub['day'],
            'time_start': start,
            'time_end': end,
          });
        }
      }

      // 1. Assign the subjects with full allocation coordinates
      await _service.batchAssignSubjects(studyLoads);

      // 2. Transmit status to Accounting for assessment billing
      for (String sId in targetIds) {
        await _service.client
            .from('student_details')
            .update({'enrollment_status': 'Assessment'}).eq('profile_id', sId);
      }

      if (mounted) {
        setState(() {
          _activeStep = 3;
          _selectedStudentIds.clear();
          _assignedSubjects = [];
          _isContextLoading = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isContextLoading = false);
        _showToast("Sync Error: $e", Colors.redAccent);
      }
    }
  }

  void _addSubjectToSession() {
    if (_selectedSubjectId == null || _autoFilledFacultyId == null) return;

    final subject = _subjectCatalog
        .firstWhere((s) => s['id'].toString() == _selectedSubjectId);

    setState(() {
      _assignedSubjects.add({
        "id": subject['id'],
        "code": subject['code'],
        "title": subject['name'],
        "units": subject['units'],
        "professor_id": _autoFilledFacultyId,
        "professor_name": _autoFilledFacultyName,
        "block": _selectedBlock,
        "room": _selectedRoom,
        "semester": _selectedSemester,
        "day": _autoFilledDay,
        "time": _autoFilledTime,
      });
      _selectedSubjectId = null;
      _autoFilledFacultyId = null;
      _autoFilledFacultyName = null;
      _autoFilledDay = null;
      _autoFilledTime = null;
    });
  }

  @override
  Widget build(BuildContext context) {
    final textColor = widget.isDarkMode ? Colors.white : pViolet;
    final bgColor = widget.isDarkMode ? surfaceDark : Colors.white;

    if (_isContextLoading) {
      return const Center(child: CircularProgressIndicator(color: aViolet));
    }
    if (_errorMessage != null) {
      return _buildErrorState(_errorMessage!, textColor);
    }

    return SingleChildScrollView(
      physics: const BouncingScrollPhysics(),
      padding: const EdgeInsets.all(40),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildHeader(textColor),
          const SizedBox(height: 32),
          _buildWorkflowStepper(textColor),
          const SizedBox(height: 32),
          _buildActiveModuleContent(textColor, bgColor),
        ],
      ),
    );
  }

  Widget _buildActiveModuleContent(Color textColor, Color bgColor) {
    switch (_activeStep) {
      case 0:
        return _buildStudentQueue(textColor, bgColor);
      case 1:
        return _buildSubjectLoadingInterface(textColor, bgColor);
      case 2:
        return _buildReviewModule(textColor, bgColor);
      case 3:
        return _buildHandoverSuccess(textColor, bgColor);
      default:
        return _buildStudentQueue(textColor, bgColor);
    }
  }

  Widget _buildStudentQueue(Color textColor, Color bgColor) {
    if (_chairDepartmentId == null) return _buildEmptyState(textColor);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Expanded(child: _buildSearchBar(bgColor, textColor)),
            if (_selectedStudentIds.isNotEmpty) ...[
              const SizedBox(width: 16),
              ElevatedButton.icon(
                onPressed: () => setState(() => _activeStep = 1),
                icon: const Icon(Icons.groups_rounded, size: 22),
                label: Text(
                    "BATCH ASSIGN (${_selectedStudentIds.length} STUDENTS)",
                    style: const TextStyle(
                        fontWeight: FontWeight.bold, fontSize: 14)),
                style: ElevatedButton.styleFrom(
                    backgroundColor: aViolet,
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(
                        horizontal: 24, vertical: 22),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(16))),
              ),
            ]
          ],
        ),
        const SizedBox(height: 24),
        FutureBuilder<List<Map<String, dynamic>>>(
          future: _service.getStudentQueue(_chairDepartmentId!),
          builder: (context, snapshot) {
            if (!snapshot.hasData) {
              return const Center(
                  child: CircularProgressIndicator(color: aViolet));
            }
            final list = snapshot.data!.where((s) {
              return s['fn']
                      .toString()
                      .toLowerCase()
                      .contains(_searchController.text.toLowerCase()) ||
                  s['user_id_number']
                      .toString()
                      .toLowerCase()
                      .contains(_searchController.text.toLowerCase());
            }).toList();
            if (list.isEmpty) return _buildEmptyState(textColor);

            return ListView.builder(
              shrinkWrap: true,
              physics: const NeverScrollableScrollPhysics(),
              itemCount: list.length,
              itemBuilder: (context, i) {
                final s = list[i];
                bool isSelected = _selectedStudentIds.contains(s['id']);
                final details = s['student_details'];
                Map<String, dynamic>? info =
                    (details is List && details.isNotEmpty)
                        ? details[0]
                        : details;
                bool isIrreg = info?['student_type'] == 'Irregular';

                return Container(
                  margin: const EdgeInsets.only(bottom: 12),
                  padding: const EdgeInsets.all(22),
                  decoration: BoxDecoration(
                      color: bgColor,
                      borderRadius: BorderRadius.circular(16),
                      border: Border.all(
                          color: isSelected
                              ? aViolet
                              : (widget.isDarkMode
                                  ? Colors.white10
                                  : Colors.black12))),
                  child: Row(
                    children: [
                      Checkbox(
                          value: isSelected,
                          activeColor: aViolet,
                          onChanged: (v) => setState(() => v!
                              ? _selectedStudentIds.add(s['id'])
                              : _selectedStudentIds.remove(s['id']))),
                      const SizedBox(width: 14),
                      Expanded(
                          child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                            Row(children: [
                              Text("${s['fn']} ${s['ln']}".toUpperCase(),
                                  style: TextStyle(
                                      color: textColor,
                                      fontWeight: FontWeight.bold,
                                      fontSize: 16)),
                              const SizedBox(width: 12),
                              _typeBadge(isIrreg ? 'IRREGULAR' : 'REGULAR',
                                  isIrreg ? Colors.orange : success),
                            ]),
                            const SizedBox(height: 4),
                            Text(
                                "ID: ${s['user_id_number']} • ${info?['courses']?['code'] ?? 'N/A'} • ${info?['year_levels']?['definition'] ?? 'N/A'}",
                                style: const TextStyle(
                                    color: Colors.blueGrey,
                                    fontSize: 13,
                                    fontWeight: FontWeight.w500))
                          ])),
                      ElevatedButton.icon(
                          onPressed: () => _handleStepTransition(s),
                          icon:
                              const Icon(Icons.arrow_forward_rounded, size: 16),
                          label: const Text("ASSIGN SUBJECTS",
                              style: TextStyle(fontWeight: FontWeight.bold)),
                          style: ElevatedButton.styleFrom(
                              backgroundColor: aViolet,
                              foregroundColor: Colors.white,
                              padding: const EdgeInsets.symmetric(
                                  horizontal: 20, vertical: 16),
                              shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(12)))),
                    ],
                  ),
                );
              },
            );
          },
        ),
      ],
    );
  }

  Widget _buildSubjectLoadingInterface(Color textColor, Color bgColor) {
    return Container(
      padding: const EdgeInsets.all(32),
      decoration: BoxDecoration(
          color: bgColor,
          borderRadius: BorderRadius.circular(24),
          border: Border.all(
              color: widget.isDarkMode ? Colors.white10 : Colors.black12)),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text("Study Load Allocation Coordinator",
                      style: GoogleFonts.inter(
                          fontWeight: FontWeight.bold,
                          color: textColor,
                          fontSize: 20)),
                  const SizedBox(height: 4),
                  Text(
                      "AUTO-COMPUTED SECTION TARGET: ${_autoGeneratedBlock ?? 'N/A'}",
                      style: const TextStyle(
                          color: aViolet,
                          fontWeight: FontWeight.w900,
                          fontSize: 13,
                          letterSpacing: 0.5)),
                ],
              ),
              Row(
                children: [
                  _templateActionMenu(textColor),
                  const SizedBox(width: 12),
                  _badge("DEPT: $_chairDepartmentName", aViolet),
                ],
              ),
            ],
          ),
          const Divider(height: 48, color: Colors.white10),

          // Form Step Title
          Text("1. ADD SUBJECT & SET ALLOCATIONS",
              style: TextStyle(
                  color: aViolet,
                  fontWeight: FontWeight.bold,
                  fontSize: 13,
                  letterSpacing: 1)),
          const SizedBox(height: 16),

          // Primary Inputs Rows
          LayoutBuilder(builder: (context, constraints) {
            double dropWidth = (constraints.maxWidth - 24) / 3;
            return Wrap(
              spacing: 12,
              runSpacing: 16,
              crossAxisAlignment: WrapCrossAlignment.end,
              children: [
                SizedBox(
                  width: dropWidth,
                  child: _buildMapDropdown("Course Subject Catalog",
                      _selectedSubjectId, _subjectCatalog, (v) {
                    setState(() => _selectedSubjectId = v);
                    if (v != null) _autoFillFromMasterSchedule(v);
                  }),
                ),
                _readOnlyField(
                    "Assigned Faculty",
                    _autoFilledFacultyName ?? "Select Course Subject",
                    dropWidth),
                _readOnlyField(
                    "Time Schedule",
                    "${_autoFilledDay ?? ''} ${_autoFilledTime ?? ''}",
                    dropWidth),

                // NEW Dropdown: Room selection
                _buildFormDropdown(
                    "Allocated Room", _selectedRoom, _availableRooms, (v) {
                  setState(() => _selectedRoom = v!);
                }, dropWidth),

                // NEW Dropdown: Semester selection
                _buildFormDropdown("Academic Term / Semester",
                    _selectedSemester, _availableSemesters, (v) {
                  setState(() => _selectedSemester = v!);
                }, dropWidth),

                // NEW Dropdown: Block / Section selection
                _buildFormDropdown(
                    "Section Block", _selectedBlock, _availableBlocks, (v) {
                  setState(() => _selectedBlock = v!);
                }, dropWidth - 68),

                Container(
                  margin: const EdgeInsets.only(bottom: 2),
                  child: IconButton(
                    onPressed: _addSubjectToSession,
                    icon: const Icon(Icons.add_circle_rounded,
                        color: success, size: 48),
                  ),
                ),
              ],
            );
          }),

          const SizedBox(height: 48),
          Text("2. CURRENT SESSION ALLOCATIONS",
              style: TextStyle(
                  color: textColor.withOpacity(0.7),
                  fontWeight: FontWeight.bold,
                  fontSize: 13,
                  letterSpacing: 1)),
          const SizedBox(height: 16),
          _buildAssignedList(textColor),
          const SizedBox(height: 32),
          Row(mainAxisAlignment: MainAxisAlignment.end, children: [
            Text("Total Selected Units: $_totalUnits",
                style: TextStyle(
                    color: textColor,
                    fontWeight: FontWeight.bold,
                    fontFamily: 'monospace',
                    fontSize: 18)),
            const SizedBox(width: 24),
            ElevatedButton.icon(
                onPressed: _assignedSubjects.isEmpty
                    ? null
                    : () => setState(() => _activeStep = 2),
                icon: const Icon(Icons.verified_user_rounded, size: 18),
                label: const Text("VALIDATE & REVIEW STUDY LOAD",
                    style:
                        TextStyle(fontWeight: FontWeight.bold, fontSize: 14)),
                style: ElevatedButton.styleFrom(
                    backgroundColor: success,
                    foregroundColor: Colors.black,
                    padding: const EdgeInsets.symmetric(
                        horizontal: 24, vertical: 22),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(16)))),
          ]),
        ],
      ),
    );
  }

  Widget _readOnlyField(String label, String value, double width) => SizedBox(
        width: width,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(label.toUpperCase(),
                style: const TextStyle(
                    fontSize: 10,
                    fontWeight: FontWeight.bold,
                    color: Colors.blueGrey,
                    letterSpacing: 1)),
            const SizedBox(height: 8),
            Container(
              height: 52,
              width: double.infinity,
              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 14),
              decoration: BoxDecoration(
                  color: widget.isDarkMode
                      ? Colors.white.withOpacity(0.04)
                      : Colors.grey.shade200,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(
                      color:
                          widget.isDarkMode ? Colors.white10 : Colors.black12)),
              child: Text(value,
                  style: TextStyle(
                      color:
                          widget.isDarkMode ? Colors.white70 : Colors.black87,
                      fontSize: 13,
                      fontWeight: FontWeight.bold,
                      overflow: TextOverflow.ellipsis)),
            ),
          ],
        ),
      );

  Widget _buildFormDropdown(String label, String currentVal,
      List<String> options, ValueChanged<String?> onChanged, double width) {
    final dropBg = widget.isDarkMode
        ? Colors.white.withOpacity(0.04)
        : Colors.grey.shade200;
    final dropBorder = widget.isDarkMode ? Colors.white10 : Colors.black12;

    // Safety: ensure currentVal is one of the options to prevent DropdownButton assertion crashes
    final List<String> safeOptions = List.from(options);
    if (!safeOptions.contains(currentVal)) {
      safeOptions.add(currentVal);
    }

    return SizedBox(
      width: width,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(label.toUpperCase(),
              style: const TextStyle(
                  color: Colors.blueGrey,
                  fontSize: 10,
                  fontWeight: FontWeight.bold,
                  letterSpacing: 1)),
          const SizedBox(height: 8),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 14),
            height: 52,
            decoration: BoxDecoration(
              color: dropBg,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: dropBorder),
            ),
            child: DropdownButtonHideUnderline(
              child: DropdownButton<String>(
                value: currentVal,
                isExpanded: true,
                dropdownColor:
                    widget.isDarkMode ? const Color(0xFF1E1B4B) : Colors.white,
                icon: const Icon(Icons.arrow_drop_down_rounded,
                    color: aViolet, size: 28),
                style: TextStyle(
                    color: widget.isDarkMode ? Colors.white : pViolet,
                    fontWeight: FontWeight.bold,
                    fontSize: 13),
                items: safeOptions
                    .map((opt) => DropdownMenuItem(
                          value: opt,
                          child: Text(opt),
                        ))
                    .toList(),
                onChanged: onChanged,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _templateActionMenu(Color textColor) {
    return PopupMenuButton<String>(
      tooltip: "Load Templates",
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 10),
        decoration: BoxDecoration(
            color: aViolet.withOpacity(0.1),
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: aViolet.withOpacity(0.3))),
        child: const Row(
          children: [
            Icon(Icons.layers_rounded, size: 18, color: aViolet),
            const SizedBox(width: 8),
            Text("TEMPLATES",
                style: TextStyle(
                    color: aViolet,
                    fontSize: 12,
                    fontWeight: FontWeight.bold,
                    letterSpacing: 0.5)),
          ],
        ),
      ),
      onSelected: (val) {
        if (val == "save_current") {
          _showSaveTemplateDialog();
        } else {
          final template = _localTemplates.firstWhere((t) => t['id'] == val);
          _applyTemplate(template);
        }
      },
      itemBuilder: (context) => [
        const PopupMenuItem(
            value: "save_current",
            child: Row(children: [
              Icon(Icons.save_rounded, size: 18, color: success),
              SizedBox(width: 8),
              Text("Save Current as Template",
                  style: TextStyle(fontWeight: FontWeight.bold))
            ])),
        const PopupMenuDivider(),
        if (_localTemplates.isEmpty)
          const PopupMenuItem(
              enabled: false,
              child: Text("No saved templates",
                  style: TextStyle(color: Colors.grey, fontSize: 12))),
        ..._localTemplates
            .map((t) => PopupMenuItem(value: t['id'], child: Text(t['name']))),
      ],
    );
  }

  void _showSaveTemplateDialog() {
    final nameCtrl = TextEditingController();
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: surfaceDark,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
        title: const Text("Save Load Template",
            style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
        content: TextField(
          controller: nameCtrl,
          autofocus: true,
          style: const TextStyle(color: Colors.white),
          decoration: const InputDecoration(
              hintText: "Enter Template Name (e.g. BSIT-2A Regular)",
              hintStyle: TextStyle(color: Colors.white30)),
        ),
        actions: [
          TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text("CANCEL",
                  style: TextStyle(
                      color: Colors.blueGrey, fontWeight: FontWeight.bold))),
          ElevatedButton(
              onPressed: () {
                _saveAsTemplate(nameCtrl.text);
                Navigator.pop(context);
              },
              style: ElevatedButton.styleFrom(
                  backgroundColor: aViolet, foregroundColor: Colors.white),
              child: const Text("SAVE TEMPLATE",
                  style: TextStyle(fontWeight: FontWeight.bold))),
        ],
      ),
    );
  }

  Widget _buildAssignedList(Color textColor) {
    if (_assignedSubjects.isEmpty) {
      return Center(
          child: Padding(
        padding: const EdgeInsets.symmetric(vertical: 40),
        child: Text("No subjects added to current advising session.",
            style: TextStyle(
                color: textColor.withOpacity(0.3),
                fontWeight: FontWeight.bold,
                fontSize: 14)),
      ));
    }
    return Column(
      children: List.generate(_assignedSubjects.length, (i) {
        final s = _assignedSubjects[i];
        return Container(
            margin: const EdgeInsets.only(bottom: 12),
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
                color: widget.isDarkMode
                    ? Colors.white.withOpacity(0.02)
                    : Colors.grey.shade100,
                border: Border.all(
                    color: widget.isDarkMode
                        ? Colors.white10
                        : Colors.black.withOpacity(0.05)),
                borderRadius: BorderRadius.circular(16)),
            child: Row(
              children: [
                const Icon(Icons.import_contacts_rounded,
                    size: 20, color: aViolet),
                const SizedBox(width: 16),
                Expanded(
                    flex: 2,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(s['code'],
                            style: const TextStyle(
                                color: aViolet,
                                fontWeight: FontWeight.bold,
                                fontSize: 15)),
                        const SizedBox(height: 2),
                        Text(s['title'],
                            style: const TextStyle(
                                color: Colors.blueGrey,
                                fontSize: 12,
                                overflow: TextOverflow.ellipsis)),
                      ],
                    )),
                Expanded(
                    flex: 2,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(s['professor_name'],
                            style: TextStyle(
                                color: textColor,
                                fontSize: 13,
                                fontWeight: FontWeight.bold)),
                        const SizedBox(height: 2),
                        Text("SCHEDULE: ${s['day']} ${s['time']}",
                            style: const TextStyle(
                                color: Colors.blueGrey, fontSize: 11)),
                      ],
                    )),
                Expanded(
                    flex: 2,
                    child: Row(
                      children: [
                        _badge("RM: ${s['room']}", aViolet),
                        const SizedBox(width: 8),
                        _badge("${s['block']}", success),
                      ],
                    )),
                IconButton(
                    onPressed: () =>
                        setState(() => _assignedSubjects.removeAt(i)),
                    icon: const Icon(Icons.delete_outline_rounded,
                        size: 22, color: Colors.redAccent)),
              ],
            ));
      }),
    );
  }

  Widget _buildReviewModule(Color textColor, Color bgColor) {
    return Container(
      padding: const EdgeInsets.all(40),
      decoration: BoxDecoration(
          color: bgColor,
          borderRadius: BorderRadius.circular(24),
          border: Border.all(
              color: widget.isDarkMode ? Colors.white10 : Colors.black12)),
      child: Column(
        children: [
          const Icon(Icons.verified_user_rounded, color: aViolet, size: 56),
          const SizedBox(height: 24),
          Text("Academic Compliance Audit Review",
              style: GoogleFonts.inter(
                  fontWeight: FontWeight.w900, fontSize: 20, color: textColor)),
          const SizedBox(height: 8),
          const Text(
              "Verify student academic parameters prior to accounting ledger billing handshake.",
              style: TextStyle(color: Colors.blueGrey, fontSize: 14)),
          const SizedBox(height: 32),
          _auditRow("Faculty Workload Availability Verified", true),
          _auditRow("Class Section Schedule Room Conflicted Checked", true),
          _auditRow("Section Block Density Check (Max 50)", true),
          const SizedBox(height: 40),
          SizedBox(
              width: double.infinity,
              height: 65,
              child: ElevatedButton.icon(
                  onPressed: _finalizeStudyLoads,
                  icon: const Icon(Icons.send_rounded, size: 18),
                  label: const Text("APPROVE & TRANSMIT TO ACCOUNTING",
                      style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 15,
                          letterSpacing: 0.5)),
                  style: ElevatedButton.styleFrom(
                      backgroundColor: success,
                      foregroundColor: Colors.black,
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(16))))),
        ],
      ),
    );
  }

  Widget _buildHandoverSuccess(Color textColor, Color bgColor) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.symmetric(vertical: 48),
        child: Column(children: [
          const Icon(Icons.autorenew_rounded, color: success, size: 72),
          const SizedBox(height: 24),
          Text("Academic Handover Complete",
              style: GoogleFonts.inter(
                  fontSize: 24, fontWeight: FontWeight.w900, color: textColor)),
          const SizedBox(height: 6),
          const Text(
              "Advising parameters & accounting ledger successfully reconciled.",
              style: TextStyle(color: Colors.blueGrey, fontSize: 15)),
          const SizedBox(height: 40),
          ElevatedButton.icon(
              onPressed: () {
                setState(() {
                  _activeStep = 0;
                  _assignedSubjects.clear();
                  _selectedStudentIds.clear();
                  _initChairContext();
                });
              },
              icon: const Icon(Icons.queue_rounded, size: 18),
              label: const Text("RETURN TO STUDENT QUEUE",
                  style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14)),
              style: ElevatedButton.styleFrom(
                  backgroundColor: aViolet,
                  foregroundColor: Colors.white,
                  padding:
                      const EdgeInsets.symmetric(horizontal: 24, vertical: 18),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(14))))
        ]),
      ),
    );
  }

  Widget _buildHeader(Color text) => Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Text("Curriculum Review Console",
                style: GoogleFonts.inter(
                    fontSize: 34,
                    fontWeight: FontWeight.w900,
                    color: text,
                    letterSpacing: -1.2)),
            const SizedBox(height: 6),
            Text(
                "Oversight Department Node: ${_chairDepartmentName ?? 'Academic Unit'}",
                style: TextStyle(
                    color: Colors.blueGrey.withOpacity(0.9),
                    fontSize: 16,
                    fontWeight: FontWeight.bold))
          ]),
        ],
      );

  Widget _buildSearchBar(Color bg, Color text) => Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
      decoration: BoxDecoration(
          color: bg,
          borderRadius: BorderRadius.circular(16),
          border: Border.all(
              color: widget.isDarkMode ? Colors.white10 : Colors.black12)),
      child: TextField(
          controller: _searchController,
          onChanged: (v) => setState(() {}),
          style:
              TextStyle(color: text, fontSize: 15, fontWeight: FontWeight.w500),
          decoration: const InputDecoration(
              hintText: "Search name or student ID number...",
              hintStyle: TextStyle(color: Colors.blueGrey, fontSize: 15),
              prefixIcon:
                  Icon(Icons.search_rounded, size: 22, color: Colors.blueGrey),
              border: InputBorder.none)));

  Widget _buildMapDropdown(String label, String? value,
          List<Map<String, dynamic>> items, Function(String?) onChanged) =>
      Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Text(label.toUpperCase(),
            style: const TextStyle(
                fontSize: 10,
                fontWeight: FontWeight.bold,
                color: Colors.blueGrey,
                letterSpacing: 1)),
        const SizedBox(height: 8),
        Container(
            padding: const EdgeInsets.symmetric(horizontal: 14),
            height: 52,
            decoration: BoxDecoration(
                color: widget.isDarkMode
                    ? Colors.white.withOpacity(0.04)
                    : Colors.grey.shade200,
                border: Border.all(
                    color: widget.isDarkMode ? Colors.white10 : Colors.black12),
                borderRadius: BorderRadius.circular(12)),
            child: DropdownButtonHideUnderline(
                child: DropdownButton<String>(
                    value: (value != null &&
                            items.any((i) => i['id'].toString() == value))
                        ? value
                        : null,
                    isExpanded: true,
                    dropdownColor:
                        widget.isDarkMode ? surfaceDark : Colors.white,
                    icon: const Icon(Icons.arrow_drop_down_rounded,
                        color: aViolet, size: 28),
                    style: TextStyle(
                        color: widget.isDarkMode ? Colors.white : pViolet,
                        fontWeight: FontWeight.bold,
                        fontSize: 13),
                    items: items
                        .map((i) => DropdownMenuItem(
                            value: i['id'].toString(),
                            child: Text(i['name'] ?? "${i['fn']} ${i['ln']}",
                                overflow: TextOverflow.ellipsis)))
                        .toList(),
                    onChanged: onChanged)))
      ]);

  Widget _buildWorkflowStepper(Color text) {
    final steps = [
      "Student Queue",
      "Load Advising",
      "Academic Review",
      "Handover Complete"
    ];
    return Row(
        children: List.generate(steps.length, (i) {
      bool active = i == _activeStep;
      bool done = i < _activeStep;
      return Expanded(
          child: Row(children: [
        Container(
            width: 32,
            height: 32,
            decoration: BoxDecoration(
                color: done ? success : (active ? aViolet : Colors.white10),
                shape: BoxShape.circle),
            child: Center(
                child: done
                    ? const Icon(Icons.check_rounded,
                        size: 16, color: Colors.black)
                    : Text("${i + 1}",
                        style: TextStyle(
                            color: active ? Colors.white : Colors.blueGrey,
                            fontSize: 12,
                            fontWeight: FontWeight.bold)))),
        const SizedBox(width: 8),
        Text(steps[i],
            style: TextStyle(
                color: active ? aViolet : Colors.blueGrey,
                fontSize: 13,
                fontWeight: active ? FontWeight.bold : FontWeight.normal)),
        if (i < 3)
          Expanded(
              child: Container(
                  height: 1.5,
                  color: Colors.white10,
                  margin: const EdgeInsets.symmetric(horizontal: 12))),
      ]));
    }));
  }

  Widget _buildErrorState(String error, Color text) => Center(
          child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
        const Icon(Icons.error_outline_rounded,
            color: Colors.redAccent, size: 56),
        const SizedBox(height: 16),
        Text(error,
            style: TextStyle(
                color: text, fontWeight: FontWeight.bold, fontSize: 15),
            textAlign: TextAlign.center),
        const SizedBox(height: 24),
        ElevatedButton.icon(
          onPressed: _initChairContext,
          icon: const Icon(Icons.refresh_rounded),
          label: const Text("RETRY DATABASE SYNC"),
          style: ElevatedButton.styleFrom(backgroundColor: aViolet),
        )
      ]));

  Widget _auditRow(String l, bool p) => Padding(
      padding: const EdgeInsets.only(bottom: 14),
      child: Row(children: [
        Icon(p ? Icons.check_circle_rounded : Icons.error_rounded,
            color: p ? success : Colors.orange, size: 20),
        const SizedBox(width: 12),
        Text(l,
            style: const TextStyle(
                color: Colors.blueGrey,
                fontSize: 13,
                fontWeight: FontWeight.w500)),
        const Spacer(),
        Text(p ? "PASSED" : "FAILED",
            style: TextStyle(
                color: p ? success : Colors.orange,
                fontSize: 11,
                fontWeight: FontWeight.bold,
                letterSpacing: 0.5))
      ]));

  Widget _badge(String t, Color c) => Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      decoration: BoxDecoration(
          color: c.withOpacity(0.1),
          borderRadius: BorderRadius.circular(8),
          border: Border.all(color: c.withOpacity(0.2))),
      child: Text(t,
          style:
              TextStyle(color: c, fontSize: 10, fontWeight: FontWeight.bold)));

  Widget _typeBadge(String t, Color c) => Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
          color: c.withOpacity(0.1),
          borderRadius: BorderRadius.circular(6),
          border: Border.all(color: c.withOpacity(0.2))),
      child: Text(t,
          style: TextStyle(
              color: c,
              fontSize: 9,
              fontWeight: FontWeight.w900,
              letterSpacing: 0.5)));

  Widget _buildEmptyState(Color t) => Center(
      child: Padding(
          padding: const EdgeInsets.all(40),
          child: Column(
            children: [
              Icon(Icons.people_alt_rounded,
                  size: 48, color: Colors.blueGrey.withOpacity(0.3)),
              const SizedBox(height: 12),
              Text("Student advising queue currently empty.",
                  style: TextStyle(
                      color: widget.isDarkMode
                          ? t.withOpacity(0.3)
                          : Colors.black.withOpacity(0.3),
                      fontWeight: FontWeight.bold,
                      fontSize: 15)),
            ],
          )));

  void _showToast(String m, Color c) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
        content: Text(m,
            style: const TextStyle(fontSize: 14, fontWeight: FontWeight.bold)),
        backgroundColor: c,
        behavior: SnackBarBehavior.floating,
        margin: const EdgeInsets.all(24),
        shape:
            RoundedRectangleBorder(borderRadius: BorderRadius.circular(12))));
  }
}
