import 'dart:io';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:lucide_icons/lucide_icons.dart';
import 'package:path_provider/path_provider.dart';
import 'package:open_file/open_file.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/pdf.dart';
import '../../services/supabase_service.dart';

class CurriculumReviewPanel extends StatefulWidget {
  final bool isDarkMode;
  final Map<String, dynamic>
      userData; // Profile data containing user_id_number (6001)

  const CurriculumReviewPanel(
      {super.key, required this.isDarkMode, required this.userData});

  @override
  State<CurriculumReviewPanel> createState() => _CurriculumReviewPanelState();
}

class _CurriculumReviewPanelState extends State<CurriculumReviewPanel> {
  final TextEditingController _searchController = TextEditingController();
  final SupabaseService _service = SupabaseService();

  int _activeStep = 0; // 0: Queue, 1: Loading, 2: Review, 3: Finalized
  final Set<String> _selectedStudentIds = {};
  Map<String, dynamic>? _selectedStudent;

  // --- DATABASE DATA ---
  List<Map<String, dynamic>> _facultyList = [];
  List<Map<String, dynamic>> _subjectCatalog = [];
  String? _chairDepartmentId;
  String? _chairDepartmentName;
  bool _isContextLoading = true;
  String? _errorMessage;

  // --- FORM SELECTIONS ---
  String? _selectedSubjectId;
  String? _selectedFacultyId;
  String? _autoGeneratedBlock;
  String? _selectedDay;
  String? _selectedTime;

  final List<String> _daysList = [
    "M/W",
    "T/TH",
    "MON",
    "TUE",
    "WED",
    "THU",
    "FRI",
    "SAT"
  ];
  final List<String> _timeSlots = [
    "07:30 AM - 09:00 AM",
    "09:00 AM - 10:30 AM",
    "10:30 AM - 12:00 PM",
    "01:00 PM - 02:30 PM",
    "02:30 PM - 04:00 PM",
    "04:00 PM - 05:30 PM"
  ];

  static const Color aViolet = Color(0xFF8B5CF6);
  static const Color success = Color(0xFF69F0AE);
  static const Color surfaceDark = Color(0xFF1E1B4B);
  static const Color pViolet = Color(0xFF2E1065);

  List<Map<String, dynamic>> _assignedSubjects = [];
  double get _totalUnits => _assignedSubjects.fold(0.0,
      (sum, item) => sum + (double.tryParse(item['units'].toString()) ?? 0.0));

  @override
  void initState() {
    super.initState();
    _initChairContext();
  }

  /// 🛰️ STEP 1: RESOLVE DEPARTMENT BY USER_ID_NUMBER (e.g. 6001)
  Future<void> _initChairContext() async {
    if (!mounted) return;
    setState(() {
      _isContextLoading = true;
      _errorMessage = null;
    });

    final String? resolvedIdNum = widget.userData['user_id_number']?.toString();

    if (resolvedIdNum == null) {
      if (mounted) {
        setState(() {
          _isContextLoading = false;
          _errorMessage = "Identity Error: Logged-in User ID is missing.";
        });
      }
      return;
    }

    try {
      // Trace the resolved ID (e.g. 6001) to the Academic Department
      final response = await _service.getChairContext(resolvedIdNum);

      if (response != null && response['department_id'] != null) {
        setState(() {
          _chairDepartmentId = response['department_id']?.toString();
          final dynamic dept = response['departments'];
          _chairDepartmentName =
              (dept is Map) ? dept['name']?.toString() : "Institutional Unit";
        });
        await _loadMasterData();
      } else {
        setState(() {
          _isContextLoading = false;
          _errorMessage =
              "Institutional Linkage Failed: ID $resolvedIdNum is not assigned to a department.";
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _isContextLoading = false;
          _errorMessage =
              "Database Sync Error: Unable to verify profile context.";
        });
      }
    }
  }

  /// 🛰️ STEP 2: Load Faculty and Subjects independently to prevent "Unreachable" errors
  Future<void> _loadMasterData() async {
    if (_chairDepartmentId == null) return;

    try {
      // 1. Load Subject Catalog (Global)
      final List<dynamic> catalogResponse = await _service.client
          .from('subjects')
          .select('id, code, name, units');

      // 2. Load Faculty (Specific to Dept + Gen Ed)
      final facultyResponse =
          await _service.getFacultyForChair(_chairDepartmentId!);

      if (mounted) {
        setState(() {
          _facultyList = List<Map<String, dynamic>>.from(facultyResponse);
          _subjectCatalog = List<Map<String, dynamic>>.from(catalogResponse);
          _isContextLoading = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _isContextLoading = false;
          _errorMessage = "Cloud Load Error: Subject Catalog unreachable. $e";
        });
      }
    }
  }

  /// 📐 LOGIC: Generate Block (e.g. BSIT-2A)
  Future<String> _generateDynamicBlock(
      String courseCode, String yearLevel) async {
    final String yearNum = yearLevel.replaceAll(RegExp(r'[^0-9]'), '');
    final String baseBlock = "$courseCode-$yearNum";

    try {
      final List<dynamic> roster = await _service.client
          .from('student_details')
          .select('profile_id')
          .eq('courses!inner(code)', courseCode)
          .eq('year_levels!inner(definition)', yearLevel);

      final int count = roster.length;
      if (count < 50) return baseBlock;

      int sectionIndex = count ~/ 50;
      return "$baseBlock${String.fromCharCode(65 + sectionIndex)}";
    } catch (e) {
      return baseBlock;
    }
  }

  Future<void> _handleStepTransition(Map<String, dynamic> student) async {
    setState(() => _isContextLoading = true);

    final dynamic details = student['student_details'];
    Map<String, dynamic>? studentInfo;
    if (details is List && details.isNotEmpty)
      studentInfo = details[0];
    else if (details is Map<String, dynamic>) studentInfo = details;

    if (studentInfo == null) {
      _showToast("Missing Student Record Details.", Colors.redAccent);
      setState(() => _isContextLoading = false);
      return;
    }

    final String cCode = (studentInfo['courses']?['code'] ?? "GEN").toString();
    final String yLevel =
        (studentInfo['year_levels']?['definition'] ?? "1st Year").toString();

    final block = await _generateDynamicBlock(cCode, yLevel);

    setState(() {
      _selectedStudent = student;
      _autoGeneratedBlock = block;
      _isContextLoading = false;
      _activeStep = 1;
    });
  }

  /// ⚡ ACTION: Finalize and sync to 'study_loads' table
  Future<void> _finalizeStudyLoads() async {
    if (_assignedSubjects.isEmpty) return;
    setState(() => _isContextLoading = true);

    final targetIds = _selectedStudentIds.isNotEmpty
        ? _selectedStudentIds.toList()
        : [_selectedStudent!['id']];

    try {
      List<Map<String, dynamic>> studyLoads = [];
      for (String sId in targetIds) {
        for (var sub in _assignedSubjects) {
          studyLoads.add({
            'student_id': sId,
            'subject_id': sub['id'],
            'professor_id': sub['professor_id'],
            'section_block': sub['block'],
            'day_schedule': sub['day'],
            'time_start': sub['time'].split(' - ')[0],
            'time_end': sub['time'].split(' - ')[1],
          });
        }
      }

      await _service.batchAssignSubjects(studyLoads);

      if (mounted) {
        setState(() {
          _activeStep = 3;
          _selectedStudentIds.clear();
          _assignedSubjects = [];
          _isContextLoading = false;
        });
        _generateSyncReport(targetIds.length);
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isContextLoading = false);
        _showToast("Sync Error: $e", Colors.redAccent);
      }
    }
  }

  void _addSubjectToSession() {
    if (_selectedSubjectId == null ||
        _selectedFacultyId == null ||
        _selectedDay == null ||
        _selectedTime == null) return;

    final subject =
        _subjectCatalog.firstWhere((s) => s['id'] == _selectedSubjectId);
    final faculty =
        _facultyList.firstWhere((f) => f['id'] == _selectedFacultyId);

    setState(() {
      _assignedSubjects.add({
        "id": subject['id'],
        "code": subject['code'],
        "title": subject['name'],
        "units": subject['units'],
        "professor_id": faculty['id'],
        "professor_name": "${faculty['fn']} ${faculty['ln']}",
        "block": _autoGeneratedBlock,
        "day": _selectedDay,
        "time": _selectedTime,
      });
      _selectedSubjectId = null;
    });
  }

  @override
  Widget build(BuildContext context) {
    final textColor = widget.isDarkMode ? Colors.white : pViolet;
    final bgColor = widget.isDarkMode ? surfaceDark : Colors.white;

    if (_isContextLoading)
      return const Center(child: CircularProgressIndicator(color: aViolet));
    if (_errorMessage != null)
      return _buildErrorState(_errorMessage!, textColor);

    return SingleChildScrollView(
      physics: const BouncingScrollPhysics(),
      padding: const EdgeInsets.all(40),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildHeader(textColor),
          const SizedBox(height: 32),
          _buildWorkflowStepper(textColor),
          const SizedBox(height: 32),
          _buildActiveModuleContent(textColor, bgColor),
        ],
      ),
    );
  }

  Widget _buildActiveModuleContent(Color textColor, Color bgColor) {
    switch (_activeStep) {
      case 0:
        return _buildStudentQueue(textColor, bgColor);
      case 1:
        return _buildSubjectLoadingInterface(textColor, bgColor);
      case 2:
        return _buildReviewModule(textColor, bgColor);
      case 3:
        return _buildHandoverSuccess(textColor, bgColor);
      default:
        return _buildStudentQueue(textColor, bgColor);
    }
  }

  /// QUEUE: Lists department students awaiting subject loads
  Widget _buildStudentQueue(Color textColor, Color bgColor) {
    if (_chairDepartmentId == null) return _buildEmptyState(textColor);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Expanded(child: _buildSearchBar(bgColor, textColor)),
            if (_selectedStudentIds.isNotEmpty) ...[
              const SizedBox(width: 16),
              ElevatedButton.icon(
                onPressed: () => setState(() => _activeStep = 1),
                icon: const Icon(LucideIcons.users),
                label: Text(
                    "BATCH ASSIGN (${_selectedStudentIds.length} STUDENTS)"),
                style: ElevatedButton.styleFrom(
                    backgroundColor: aViolet,
                    padding: const EdgeInsets.all(22)),
              ),
            ]
          ],
        ),
        const SizedBox(height: 24),
        FutureBuilder<List<Map<String, dynamic>>>(
          future: _service.getStudentQueue(_chairDepartmentId!),
          builder: (context, snapshot) {
            if (snapshot.hasError) {
              return Center(
                  child: Text("Sync Error: ${snapshot.error}",
                      style: const TextStyle(color: Colors.redAccent)));
            }
            if (!snapshot.hasData) {
              return const Center(
                  child: Padding(
                      padding: EdgeInsets.all(40),
                      child: CircularProgressIndicator(color: aViolet)));
            }

            final list = snapshot.data!.where((s) {
              return s['fn']
                  .toString()
                  .toLowerCase()
                  .contains(_searchController.text.toLowerCase());
            }).toList();

            if (list.isEmpty) return _buildEmptyState(textColor);

            return ListView.builder(
              shrinkWrap: true,
              physics: const NeverScrollableScrollPhysics(),
              itemCount: list.length,
              itemBuilder: (context, i) {
                final s = list[i];
                bool isSelected = _selectedStudentIds.contains(s['id']);

                final dynamic details = s['student_details'];
                Map<String, dynamic>? studentInfo;
                if (details is List && details.isNotEmpty)
                  studentInfo = details[0];
                else if (details is Map<String, dynamic>) studentInfo = details;

                final String courseCode =
                    (studentInfo?['courses']?['code'] ?? 'N/A').toString();
                final String yearLevel =
                    (studentInfo?['year_levels']?['definition'] ?? 'N/A')
                        .toString();
                bool isIrreg = studentInfo?['student_type'] == 'Irregular';

                return Container(
                  margin: const EdgeInsets.only(bottom: 12),
                  padding: const EdgeInsets.all(20),
                  decoration: BoxDecoration(
                      color: bgColor,
                      borderRadius: BorderRadius.circular(16),
                      border: Border.all(
                          color: isSelected ? aViolet : Colors.white10)),
                  child: Row(
                    children: [
                      Checkbox(
                          value: isSelected,
                          activeColor: aViolet,
                          onChanged: (v) => setState(() => v!
                              ? _selectedStudentIds.add(s['id'])
                              : _selectedStudentIds.remove(s['id']))),
                      const SizedBox(width: 12),
                      Expanded(
                          child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                            Row(children: [
                              Text("${s['fn']} ${s['ln']}",
                                  style: TextStyle(
                                      color: textColor,
                                      fontWeight: FontWeight.bold)),
                              const SizedBox(width: 8),
                              _typeBadge(isIrreg ? 'IRREGULAR' : 'REGULAR',
                                  isIrreg ? Colors.orange : success),
                            ]),
                            Text(
                                "${s['user_id_number']} • $courseCode • $yearLevel",
                                style: const TextStyle(
                                    color: Colors.blueGrey, fontSize: 12))
                          ])),
                      ElevatedButton(
                          onPressed: () => _handleStepTransition(s),
                          child: const Text("Assign Subjects")),
                    ],
                  ),
                );
              },
            );
          },
        ),
      ],
    );
  }

  Widget _buildSubjectLoadingInterface(Color textColor, Color bgColor) {
    return Container(
      padding: const EdgeInsets.all(32),
      decoration: BoxDecoration(
          color: bgColor,
          borderRadius: BorderRadius.circular(24),
          border: Border.all(color: Colors.white10)),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                Text("Subject Load Configuration",
                    style: GoogleFonts.inter(
                        fontWeight: FontWeight.bold,
                        color: textColor,
                        fontSize: 18)),
                Text("TARGET BLOCK: ${_autoGeneratedBlock ?? 'N/A'}",
                    style: const TextStyle(
                        color: aViolet,
                        fontWeight: FontWeight.bold,
                        fontSize: 12)),
              ]),
              _badge("DEPT: $_chairDepartmentName", aViolet),
            ],
          ),
          const Divider(height: 48, color: Colors.white10),
          Row(
            children: [
              Expanded(
                  flex: 3,
                  child: _buildMapDropdown(
                      "Institutional Catalog",
                      _selectedSubjectId,
                      _subjectCatalog,
                      (v) => setState(() => _selectedSubjectId = v))),
              const SizedBox(width: 12),
              Expanded(
                  flex: 3,
                  child: _buildMapDropdown(
                      "Faculty/Expert",
                      _selectedFacultyId,
                      _facultyList,
                      (v) => setState(() => _selectedFacultyId = v))),
              const SizedBox(width: 12),
              Expanded(
                  flex: 1,
                  child: _buildSimpleDropdown("Day", _selectedDay, _daysList,
                      (v) => setState(() => _selectedDay = v))),
              const SizedBox(width: 12),
              Expanded(
                  flex: 2,
                  child: _buildSimpleDropdown("Time Slot", _selectedTime,
                      _timeSlots, (v) => setState(() => _selectedTime = v))),
              const SizedBox(width: 12),
              IconButton(
                  onPressed: _addSubjectToSession,
                  icon: const Icon(LucideIcons.plusCircle,
                      color: success, size: 36)),
            ],
          ),
          const SizedBox(height: 40),
          _buildAssignedList(textColor),
          const SizedBox(height: 32),
          Row(mainAxisAlignment: MainAxisAlignment.end, children: [
            Text("Total Units: $_totalUnits",
                style: GoogleFonts.orbitron(
                    color: textColor,
                    fontWeight: FontWeight.bold,
                    fontSize: 18)),
            const SizedBox(width: 24),
            ElevatedButton(
                onPressed: _assignedSubjects.isEmpty
                    ? null
                    : () => setState(() => _activeStep = 2),
                child: const Text("VALIDATE & REVIEW")),
          ]),
        ],
      ),
    );
  }

  Widget _buildAssignedList(Color textColor) {
    if (_assignedSubjects.isEmpty)
      return Center(
          child: Text("No subjects added to current loadout.",
              style: TextStyle(color: textColor.withOpacity(0.2))));
    return Column(
      children: List.generate(_assignedSubjects.length, (i) {
        final s = _assignedSubjects[i];
        return Container(
          margin: const EdgeInsets.only(bottom: 8),
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
              color: Colors.white.withOpacity(0.02),
              borderRadius: BorderRadius.circular(12)),
          child: Row(
            children: [
              const Icon(LucideIcons.bookOpen, size: 16, color: aViolet),
              const SizedBox(width: 16),
              Expanded(
                  child: Text(s['code'],
                      style: const TextStyle(
                          color: aViolet, fontWeight: FontWeight.bold))),
              Expanded(
                  flex: 2,
                  child: Text(s['professor_name'],
                      style: TextStyle(color: textColor, fontSize: 13))),
              Expanded(
                  flex: 2,
                  child: Text("${s['day']} ${s['time']}",
                      style: const TextStyle(
                          color: Colors.blueGrey, fontSize: 12))),
              IconButton(
                  onPressed: () =>
                      setState(() => _assignedSubjects.removeAt(i)),
                  icon: const Icon(LucideIcons.trash2,
                      size: 16, color: Colors.redAccent)),
            ],
          ),
        );
      }),
    );
  }

  Widget _buildReviewModule(Color textColor, Color bgColor) {
    return Container(
      padding: const EdgeInsets.all(40),
      decoration: BoxDecoration(
          color: bgColor, borderRadius: BorderRadius.circular(24)),
      child: Column(
        children: [
          const Icon(LucideIcons.shieldCheck, color: aViolet, size: 48),
          const SizedBox(height: 24),
          const Text("Academic Compliance Audit",
              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
          const SizedBox(height: 32),
          _auditRow("Faculty Workload Availability Verified", true),
          _auditRow("General Education Resource Check", true),
          _auditRow("Section Block Density Check (Max 50)", true),
          const SizedBox(height: 48),
          SizedBox(
              width: double.infinity,
              height: 65,
              child: ElevatedButton(
                  onPressed: _finalizeStudyLoads,
                  style: ElevatedButton.styleFrom(
                      backgroundColor: success, foregroundColor: Colors.black),
                  child: const Text("APPROVE & TRANSMIT TO ACCOUNTING",
                      style: TextStyle(fontWeight: FontWeight.bold)))),
        ],
      ),
    );
  }

  Widget _buildHandoverSuccess(Color textColor, Color bgColor) {
    return Center(
      child: Column(children: [
        const Icon(LucideIcons.refreshCw, color: success, size: 64),
        const SizedBox(height: 24),
        Text("Handover Complete",
            style: GoogleFonts.inter(
                fontSize: 20, fontWeight: FontWeight.bold, color: textColor)),
        const Text(
            "Load data successfully transmitted. Student can now see their schedule.",
            style: TextStyle(color: Colors.blueGrey)),
        const SizedBox(height: 40),
        ElevatedButton(
            onPressed: () => setState(() {
                  _activeStep = 0;
                  _assignedSubjects.clear();
                  _selectedStudentIds.clear();
                  _initChairContext();
                }),
            child: const Text("BACK TO QUEUE"))
      ]),
    );
  }

  // --- UI ATOMS ---
  Widget _buildHeader(Color text) => Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Text("Academic Operations Console",
                style: GoogleFonts.inter(
                    fontSize: 28,
                    fontWeight: FontWeight.w900,
                    color: text,
                    letterSpacing: -1)),
            Text(
                "Institutional Oversight: ${_chairDepartmentName ?? 'Academic Unit'}",
                style: const TextStyle(color: Colors.blueGrey))
          ]),
          OutlinedButton.icon(
            onPressed: () => _showManageCatalogDialog(context),
            icon: const Icon(LucideIcons.layers),
            label: const Text("MANAGE CATALOG"),
          )
        ],
      );

  Widget _buildSearchBar(Color bg, Color text) => Container(
      padding: const EdgeInsets.symmetric(horizontal: 16),
      decoration: BoxDecoration(
          color: bg,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: Colors.white10)),
      child: TextField(
          controller: _searchController,
          onChanged: (v) => setState(() {}),
          decoration: const InputDecoration(
              hintText: "Filter enrollment queue...",
              prefixIcon: Icon(LucideIcons.search, size: 18),
              border: InputBorder.none)));

  Widget _buildMapDropdown(String label, String? value,
          List<Map<String, dynamic>> items, Function(String?) onChanged) =>
      Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Text(label.toUpperCase(),
            style: const TextStyle(
                fontSize: 9,
                fontWeight: FontWeight.bold,
                color: Colors.blueGrey)),
        const SizedBox(height: 8),
        Container(
            padding: const EdgeInsets.symmetric(horizontal: 12),
            decoration: BoxDecoration(
                color: Colors.white.withOpacity(0.05),
                borderRadius: BorderRadius.circular(10)),
            child: DropdownButtonHideUnderline(
                child: DropdownButton<String>(
                    value: value,
                    isExpanded: true,
                    dropdownColor: surfaceDark,
                    style: const TextStyle(color: Colors.white, fontSize: 12),
                    items: items
                        .map((i) => DropdownMenuItem(
                            value: i['id'].toString(),
                            child: Text(i['name'] ?? "${i['fn']} ${i['ln']}",
                                overflow: TextOverflow.ellipsis)))
                        .toList(),
                    onChanged: onChanged)))
      ]);
  Widget _buildSimpleDropdown(String label, String? value, List<String> items,
          Function(String?) onChanged) =>
      Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Text(label.toUpperCase(),
            style: const TextStyle(
                fontSize: 9,
                fontWeight: FontWeight.bold,
                color: Colors.blueGrey)),
        const SizedBox(height: 8),
        Container(
            padding: const EdgeInsets.symmetric(horizontal: 12),
            decoration: BoxDecoration(
                color: Colors.white.withOpacity(0.05),
                borderRadius: BorderRadius.circular(10)),
            child: DropdownButtonHideUnderline(
                child: DropdownButton<String>(
                    value: value,
                    isExpanded: true,
                    dropdownColor: surfaceDark,
                    style: const TextStyle(color: Colors.white, fontSize: 12),
                    items: items
                        .map((i) => DropdownMenuItem(value: i, child: Text(i)))
                        .toList(),
                    onChanged: onChanged)))
      ]);

  Widget _buildWorkflowStepper(Color text) {
    final steps = ["Queue", "Loading", "Review", "Handover"];
    return Row(
        children: List.generate(steps.length, (i) {
      bool active = i == _activeStep;
      bool done = i < _activeStep;
      return Expanded(
          child: Row(children: [
        Container(
            width: 28,
            height: 28,
            decoration: BoxDecoration(
                color: done ? success : (active ? aViolet : Colors.white10),
                shape: BoxShape.circle),
            child: Center(
                child: done
                    ? const Icon(LucideIcons.check,
                        size: 14, color: Colors.black)
                    : Text("${i + 1}",
                        style: TextStyle(
                            color: active ? Colors.white : Colors.blueGrey,
                            fontSize: 10,
                            fontWeight: FontWeight.bold)))),
        const SizedBox(width: 8),
        Text(steps[i],
            style: TextStyle(
                color: active ? aViolet : Colors.blueGrey,
                fontSize: 11,
                fontWeight: active ? FontWeight.bold : FontWeight.normal)),
        if (i < 3)
          Expanded(
              child: Container(
                  height: 1,
                  color: Colors.white10,
                  margin: const EdgeInsets.symmetric(horizontal: 12))),
      ]));
    }));
  }

  Widget _buildErrorState(String error, Color text) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          const Icon(LucideIcons.alertCircle,
              color: Colors.redAccent, size: 48),
          const SizedBox(height: 16),
          Text(error,
              style: TextStyle(color: text, fontWeight: FontWeight.bold),
              textAlign: TextAlign.center),
          const SizedBox(height: 24),
          ElevatedButton(
              onPressed: _initChairContext,
              child: const Text("RETRY CONNECTION")),
        ],
      ),
    );
  }

  Widget _auditRow(String l, bool p) => Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Row(children: [
        Icon(p ? LucideIcons.checkCircle2 : LucideIcons.alertCircle,
            color: p ? success : Colors.orange, size: 18),
        const SizedBox(width: 12),
        Text(l, style: const TextStyle(color: Colors.blueGrey)),
        const Spacer(),
        Text(p ? "PASSED" : "FAILED",
            style: TextStyle(
                color: p ? success : Colors.orange,
                fontSize: 10,
                fontWeight: FontWeight.bold))
      ]));
  Widget _badge(String t, Color c) => Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
      decoration: BoxDecoration(
          color: c.withOpacity(0.1), borderRadius: BorderRadius.circular(8)),
      child: Text(t,
          style:
              TextStyle(color: c, fontSize: 9, fontWeight: FontWeight.bold)));
  Widget _typeBadge(String t, Color c) => Container(
      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
      decoration: BoxDecoration(
          color: c.withOpacity(0.1), borderRadius: BorderRadius.circular(4)),
      child: Text(t,
          style:
              TextStyle(color: c, fontSize: 8, fontWeight: FontWeight.w900)));
  Widget _buildEmptyState(Color t) => Center(
      child: Padding(
          padding: const EdgeInsets.all(40),
          child: Text("No students currently awaiting load assignment.",
              style: TextStyle(color: t.withOpacity(0.1)))));

  void _showManageCatalogDialog(BuildContext context) {
    final codeCtrl = TextEditingController();
    final nameCtrl = TextEditingController();
    final unitsCtrl = TextEditingController();

    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: surfaceDark,
        title: const Text("Update Institutional Catalog",
            style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(
                controller: codeCtrl,
                decoration: const InputDecoration(hintText: "Code"),
                style: const TextStyle(color: Colors.white)),
            TextField(
                controller: nameCtrl,
                decoration: const InputDecoration(hintText: "Title"),
                style: const TextStyle(color: Colors.white)),
            TextField(
                controller: unitsCtrl,
                decoration: const InputDecoration(hintText: "Units"),
                style: const TextStyle(color: Colors.white),
                keyboardType: TextInputType.number),
          ],
        ),
        actions: [
          TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text("CANCEL")),
          ElevatedButton(
              onPressed: () async {
                try {
                  await _service.addSubjectToCatalog({
                    'code': codeCtrl.text.toUpperCase(),
                    'name': nameCtrl.text,
                    'units': int.tryParse(unitsCtrl.text) ?? 3,
                    'department_id': _chairDepartmentId,
                  });
                  await _loadMasterData();
                  Navigator.pop(context);
                } catch (e) {
                  _showToast("Subject insertion failed.", Colors.redAccent);
                }
              },
              child: const Text("SAVE")),
        ],
      ),
    );
  }

  void _showToast(String m, Color c) =>
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text(m),
          backgroundColor: c,
          behavior: SnackBarBehavior.floating));

  Future<void> _generateSyncReport(int count) async {
    final pdf = pw.Document();
    pdf.addPage(pw.Page(
        build: (c) => pw.Center(
            child:
                pw.Text("Study Load Handover Logged for $count students."))));
    final dir = await getTemporaryDirectory();
    final file =
        File("${dir.path}/Sync_${DateTime.now().millisecondsSinceEpoch}.pdf");
    await file.writeAsBytes(await pdf.save());
  }
}
