import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:lucide_icons/lucide_icons.dart';
import '../../services/supabase_service.dart';

class EnrollmentVerificationPanel extends StatefulWidget {
  final bool isDarkMode;
  final Map<String, dynamic> userData;

  const EnrollmentVerificationPanel(
      {super.key, required this.isDarkMode, required this.userData});

  @override
  State<EnrollmentVerificationPanel> createState() =>
      _EnrollmentVerificationPanelState();
}

class _EnrollmentVerificationPanelState
    extends State<EnrollmentVerificationPanel> {
  final SupabaseService _service = SupabaseService();
  List<Map<String, dynamic>> _queue = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadEnrollmentQueue();
  }

  /// 🛰️ DATABASE: Fetches applicants who have verified documents but need final enrollment clearance
  Future<void> _loadEnrollmentQueue() async {
    if (!mounted) return;
    setState(() => _isLoading = true);
    try {
      // SQL ALIGNMENT: Applicants whose status was updated to 'Verified' in the previous step
      final response = await _service.client
          .from('applicants')
          .select('*, courses(name, code)')
          .eq('status', 'Verified');

      if (mounted) {
        setState(() {
          _queue = List<Map<String, dynamic>>.from(response);
          _isLoading = false;
        });
      }
    } catch (e) {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  /// 🛰️ HANDOVER: Finalizes Admission and triggers Accounting/Registrar Handover
  Future<void> _finalizeEnrollment(Map<String, dynamic> app) async {
    try {
      // 1. Mark applicant as Admitted (This moves them out of Admissions)
      await _service.client
          .from('applicants')
          .update({'status': 'Admitted'}).eq('id', app['id']);

      // 2. RELEASE TO ACCOUNTING: Create the 2000 PHP Payment Request
      // We insert into office_requests. Accounting monitors this for payments.
      await _service.client.from('office_requests').insert({
        'qr_hash':
            'REG-${app['application_no']}-${DateTime.now().millisecondsSinceEpoch}',
        'request_type': 'Registration Fee',
        'status': 'Pending Payment',
        'amount_due': 2000.00,
        'remarks':
            'Registration fee for ${app['full_name']}. Handover generated by Admissions.',
      });

      _loadEnrollmentQueue();
      _showHandoverSuccess(app['full_name']);
    } catch (e) {
      debugPrint("Handover Error: $e");
    }
  }

  void _showHandoverSuccess(String name) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: const Color(0xFF1E1B4B),
        title: const Text("Released to Accounting",
            style: TextStyle(color: Colors.white)),
        content: Text(
            "Applicant $name has been cleared. The 2000 PHP registration fee request has been transmitted to the Accounting office.",
            style: const TextStyle(color: Colors.white70)),
        actions: [
          ElevatedButton(
            onPressed: () => Navigator.pop(context),
            style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF69F0AE),
                foregroundColor: Colors.black),
            child: const Text("CONTINUE"),
          )
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final textColor =
        widget.isDarkMode ? Colors.white : const Color(0xFF2E1065);
    final cardColor =
        widget.isDarkMode ? const Color(0xFF1E1B4B) : Colors.white;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text("Final Enrollment Handover",
            style: GoogleFonts.inter(
                fontSize: 24, fontWeight: FontWeight.w900, color: textColor)),
        const Text(
            "Verified applicants ready for the 2,000 PHP registration fee and accounting clearance.",
            style: TextStyle(color: Colors.blueGrey)),
        const SizedBox(height: 32),
        Expanded(
          child: _isLoading
              ? const Center(child: CircularProgressIndicator())
              : _queue.isEmpty
                  ? const Center(
                      child: Text("No applicants currently in handover status.",
                          style: TextStyle(color: Colors.blueGrey)))
                  : Container(
                      decoration: BoxDecoration(
                          color: cardColor,
                          borderRadius: BorderRadius.circular(24),
                          border: Border.all(color: Colors.white10)),
                      child: ListView.builder(
                        itemCount: _queue.length,
                        itemBuilder: (context, i) {
                          final app = _queue[i];
                          return ListTile(
                            contentPadding: const EdgeInsets.all(24),
                            leading: Container(
                              padding: const EdgeInsets.all(12),
                              decoration: BoxDecoration(
                                  color:
                                      const Color(0xFF69F0AE).withOpacity(0.1),
                                  shape: BoxShape.circle),
                              child: const Icon(LucideIcons.userCheck,
                                  color: Color(0xFF69F0AE)),
                            ),
                            title: Text(app['full_name'],
                                style: TextStyle(
                                    color: textColor,
                                    fontWeight: FontWeight.bold)),
                            subtitle: Text(
                                "Apply For: ${app['courses']?['name'] ?? 'N/A'} • Ref: ${app['application_no']}",
                                style: const TextStyle(color: Colors.blueGrey)),
                            trailing: ElevatedButton.icon(
                              onPressed: () => _finalizeEnrollment(app),
                              icon: const Icon(LucideIcons.send, size: 16),
                              label: const Text("RELEASE TO ACCOUNTING"),
                              style: ElevatedButton.styleFrom(
                                backgroundColor: const Color(0xFF8B5CF6),
                                padding: const EdgeInsets.symmetric(
                                    horizontal: 20, vertical: 15),
                                shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(12)),
                              ),
                            ),
                          );
                        },
                      ),
                    ),
        ),
      ],
    );
  }
}
